service: <%=project%>

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage , 'dev'}
  region: ${opt:region , 'us-west-2'}

functions:
  <%=project%>: # function name
    handler: app.serverless
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
